# Site settings
title: Jesse T. Alford
email: your-email@domain.com
description: "Changed description!"
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
